{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNPuLN0IW9XnpomchdK5/N+",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/ahzaidy/Programs/blob/main/CPSC_5440_HW21.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "id": "xGMaKqWQ7VBm",
        "outputId": "303f0e3e-8131-4b08-e4be-942e11abbf3e"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-03-07 06:00:31,059\tINFO worker.py:1672 -- Calling ray.init() again after it has already been called.\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "+-----------------------------------------------------------------------+\n",
            "| Configuration for experiment     train_cifar100_2025-03-07_06-00-33   |\n",
            "+-----------------------------------------------------------------------+\n",
            "| Search algorithm                 BasicVariantGenerator                |\n",
            "| Scheduler                        AsyncHyperBandScheduler              |\n",
            "| Number of trials                 10                                   |\n",
            "+-----------------------------------------------------------------------+\n",
            "\n",
            "View detailed results here: /root/ray_results/train_cifar100_2025-03-07_06-00-33\n",
            "To visualize your results with TensorBoard, run: `tensorboard --logdir /tmp/ray/session_2025-03-07_05-45-45_878621_2122/artifacts/2025-03-07_06-00-33/train_cifar100_2025-03-07_06-00-33/driver_artifacts`\n",
            "\n",
            "Trial status: 10 PENDING\n",
            "Current time: 2025-03-07 06:00:33. Total running time: 0s\n",
            "Logical resource usage: 0/2 CPUs, 0/0 GPUs\n",
            "+------------------------------------------------------------------------------------------------------------------+\n",
            "| Trial name                   status       units   hidden_activation     optimizer       batch_size            lr |\n",
            "+------------------------------------------------------------------------------------------------------------------+\n",
            "| train_cifar100_7b6d0_00000   PENDING        120   Sigmoid               Adam                  2000   0.00411973  |\n",
            "| train_cifar100_7b6d0_00001   PENDING        120   ReLU                  Adam                  1000   0.000810627 |\n",
            "| train_cifar100_7b6d0_00002   PENDING        240   Sigmoid               Adam                  1000   0.00814788  |\n",
            "| train_cifar100_7b6d0_00003   PENDING        240   Sigmoid               Adam                  1000   0.0836389   |\n",
            "| train_cifar100_7b6d0_00004   PENDING        120   ReLU                  Adam                  2000   0.00461581  |\n",
            "| train_cifar100_7b6d0_00005   PENDING        240   ReLU                  Adam                  2000   0.0110103   |\n",
            "| train_cifar100_7b6d0_00006   PENDING        120   Sigmoid               Adagrad               1000   0.000112485 |\n",
            "| train_cifar100_7b6d0_00007   PENDING        120   Sigmoid               Adam                  2000   0.000224907 |\n",
            "| train_cifar100_7b6d0_00008   PENDING        240   ReLU                  Adagrad               1000   0.0189111   |\n",
            "| train_cifar100_7b6d0_00009   PENDING        240   ReLU                  Adam                  1000   0.0153408   |\n",
            "+------------------------------------------------------------------------------------------------------------------+\n",
            "\n",
            "Trial train_cifar100_7b6d0_00000 started with configuration:\n",
            "+-----------------------------------------------------+\n",
            "| Trial train_cifar100_7b6d0_00000 config             |\n",
            "+-----------------------------------------------------+\n",
            "| batch_size                                     2000 |\n",
            "| hidden_activation                           Sigmoid |\n",
            "| lr                                          0.00412 |\n",
            "| optimizer                                      Adam |\n",
            "| units                                           120 |\n",
            "+-----------------------------------------------------+\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-03-07 06:00:42,839\tERROR tune_controller.py:1331 -- Trial task failed for trial train_cifar100_7b6d0_00000\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
            "    result = ray.get(future)\n",
            "             ^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
            "    return func(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/worker.py\", line 2771, in get\n",
            "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
            "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/worker.py\", line 919, in get_objects\n",
            "    raise value.as_instanceof_cause()\n",
            "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=6763, ip=172.28.0.12, actor_id=1b03fed23e4587251cd4606501000000, repr=train_cifar100)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/trainable.py\", line 330, in train\n",
            "    raise skipped from exception_cause(skipped)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/air/_internal/util.py\", line 107, in run\n",
            "    self._ret = self._target(*self._args, **self._kwargs)\n",
            "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
            "    training_func=lambda: self._trainable_func(self.config),\n",
            "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/function_trainable.py\", line 261, in _trainable_func\n",
            "    output = fn()\n",
            "             ^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/util.py\", line 130, in inner\n",
            "    return trainable(config, **fn_kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"<ipython-input-4-011711f2a57e>\", line 94, in train_cifar100\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/train/_internal/session.py\", line 663, in wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^\n",
            "TypeError: report() got an unexpected keyword argument 'loss'\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Trial train_cifar100_7b6d0_00000 errored after 0 iterations at 2025-03-07 06:00:42. Total running time: 9s\n",
            "Error file: /tmp/ray/session_2025-03-07_05-45-45_878621_2122/artifacts/2025-03-07_06-00-33/train_cifar100_2025-03-07_06-00-33/driver_artifacts/train_cifar100_7b6d0_00000_0_batch_size=2000,hidden_activation=Sigmoid,lr=0.0041,optimizer=Adam,units=120_2025-03-07_06-00-33/error.txt\n",
            "\n",
            "Trial train_cifar100_7b6d0_00001 started with configuration:\n",
            "+-----------------------------------------------------+\n",
            "| Trial train_cifar100_7b6d0_00001 config             |\n",
            "+-----------------------------------------------------+\n",
            "| batch_size                                     1000 |\n",
            "| hidden_activation                              ReLU |\n",
            "| lr                                          0.00081 |\n",
            "| optimizer                                      Adam |\n",
            "| units                                           120 |\n",
            "+-----------------------------------------------------+\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-03-07 06:00:51,214\tERROR tune_controller.py:1331 -- Trial task failed for trial train_cifar100_7b6d0_00001\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
            "    result = ray.get(future)\n",
            "             ^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
            "    return func(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/worker.py\", line 2771, in get\n",
            "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
            "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/worker.py\", line 919, in get_objects\n",
            "    raise value.as_instanceof_cause()\n",
            "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=6875, ip=172.28.0.12, actor_id=71dd19e68052187d22a339fa01000000, repr=train_cifar100)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/trainable.py\", line 330, in train\n",
            "    raise skipped from exception_cause(skipped)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/air/_internal/util.py\", line 107, in run\n",
            "    self._ret = self._target(*self._args, **self._kwargs)\n",
            "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
            "    training_func=lambda: self._trainable_func(self.config),\n",
            "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/function_trainable.py\", line 261, in _trainable_func\n",
            "    output = fn()\n",
            "             ^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/util.py\", line 130, in inner\n",
            "    return trainable(config, **fn_kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"<ipython-input-4-011711f2a57e>\", line 94, in train_cifar100\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/train/_internal/session.py\", line 663, in wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^\n",
            "TypeError: report() got an unexpected keyword argument 'loss'\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Trial train_cifar100_7b6d0_00001 errored after 0 iterations at 2025-03-07 06:00:51. Total running time: 17s\n",
            "Error file: /tmp/ray/session_2025-03-07_05-45-45_878621_2122/artifacts/2025-03-07_06-00-33/train_cifar100_2025-03-07_06-00-33/driver_artifacts/train_cifar100_7b6d0_00001_1_batch_size=1000,hidden_activation=ReLU,lr=0.0008,optimizer=Adam,units=120_2025-03-07_06-00-33/error.txt\n",
            "\n",
            "Trial train_cifar100_7b6d0_00002 started with configuration:\n",
            "+-----------------------------------------------------+\n",
            "| Trial train_cifar100_7b6d0_00002 config             |\n",
            "+-----------------------------------------------------+\n",
            "| batch_size                                     1000 |\n",
            "| hidden_activation                           Sigmoid |\n",
            "| lr                                          0.00815 |\n",
            "| optimizer                                      Adam |\n",
            "| units                                           240 |\n",
            "+-----------------------------------------------------+\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-03-07 06:01:01,314\tERROR tune_controller.py:1331 -- Trial task failed for trial train_cifar100_7b6d0_00002\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
            "    result = ray.get(future)\n",
            "             ^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
            "    return func(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/worker.py\", line 2771, in get\n",
            "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
            "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/worker.py\", line 919, in get_objects\n",
            "    raise value.as_instanceof_cause()\n",
            "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=6977, ip=172.28.0.12, actor_id=234fd8f276a94b1a852cbe8301000000, repr=train_cifar100)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/trainable.py\", line 330, in train\n",
            "    raise skipped from exception_cause(skipped)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/air/_internal/util.py\", line 107, in run\n",
            "    self._ret = self._target(*self._args, **self._kwargs)\n",
            "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
            "    training_func=lambda: self._trainable_func(self.config),\n",
            "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/function_trainable.py\", line 261, in _trainable_func\n",
            "    output = fn()\n",
            "             ^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/util.py\", line 130, in inner\n",
            "    return trainable(config, **fn_kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"<ipython-input-4-011711f2a57e>\", line 94, in train_cifar100\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/train/_internal/session.py\", line 663, in wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^\n",
            "TypeError: report() got an unexpected keyword argument 'loss'\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m *** SIGSEGV received at time=1741327261 on cpu 1 ***\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m PC: @     0x79f4f7df58fe  (unknown)  ray::gcs::TaskInfoAccessor::AsyncAddTaskEventData()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m     @     0x79f4f95d6520       1824  (unknown)\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m     @     0x79f4f7cd6ab5       1392  ray::core::worker::TaskEventBufferImpl::FlushEvents()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m     @     0x79f4f7c5f82c       1488  ray::core::CoreWorker::Disconnect()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m     @     0x79f4f7c5fbdd       1152  ray::core::CoreWorker::ForceExit()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m     @     0x79f4f7c6000f       1680  ray::core::CoreWorker::HandleKillActor()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m     @     0x79f4f7c57514        192  ray::rpc::ServerCallImpl<>::HandleRequestImpl()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m     @     0x79f4f7fe4d08       1168  EventTracker::RecordExecution()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m     @     0x79f4f7fc913e         48  std::_Function_handler<>::_M_invoke()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m     @     0x79f4f7fc95b6        112  boost::asio::detail::completion_handler<>::do_complete()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m     @     0x79f4f868fa5b        128  boost::asio::detail::scheduler::do_run_one()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m     @     0x79f4f86913d9        288  boost::asio::detail::scheduler::run()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m     @     0x79f4f8691ae2         96  boost::asio::io_context::run()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m     @     0x79f4f7bb81f1       1280  ray::core::CoreWorker::RunIOService()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m     @     0x79f4f80d6620         64  thread_proxy\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m     @     0x79f4f9628ac3  (unknown)  (unknown)\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m [2025-03-07 06:01:01,346 E 6977 7003] logging.cc:484: *** SIGSEGV received at time=1741327261 on cpu 1 ***\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m [2025-03-07 06:01:01,346 E 6977 7003] logging.cc:484: PC: @     0x79f4f7df58fe  (unknown)  ray::gcs::TaskInfoAccessor::AsyncAddTaskEventData()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m [2025-03-07 06:01:01,346 E 6977 7003] logging.cc:484:     @     0x79f4f95d6520       1824  (unknown)\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m [2025-03-07 06:01:01,346 E 6977 7003] logging.cc:484:     @     0x79f4f7cd6ab5       1392  ray::core::worker::TaskEventBufferImpl::FlushEvents()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m [2025-03-07 06:01:01,346 E 6977 7003] logging.cc:484:     @     0x79f4f7c5f82c       1488  ray::core::CoreWorker::Disconnect()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m [2025-03-07 06:01:01,346 E 6977 7003] logging.cc:484:     @     0x79f4f7c5fbdd       1152  ray::core::CoreWorker::ForceExit()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m [2025-03-07 06:01:01,346 E 6977 7003] logging.cc:484:     @     0x79f4f7c6000f       1680  ray::core::CoreWorker::HandleKillActor()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m [2025-03-07 06:01:01,346 E 6977 7003] logging.cc:484:     @     0x79f4f7c57514        192  ray::rpc::ServerCallImpl<>::HandleRequestImpl()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m [2025-03-07 06:01:01,346 E 6977 7003] logging.cc:484:     @     0x79f4f7fe4d08       1168  EventTracker::RecordExecution()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m [2025-03-07 06:01:01,346 E 6977 7003] logging.cc:484:     @     0x79f4f7fc913e         48  std::_Function_handler<>::_M_invoke()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m [2025-03-07 06:01:01,346 E 6977 7003] logging.cc:484:     @     0x79f4f7fc95b6        112  boost::asio::detail::completion_handler<>::do_complete()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m [2025-03-07 06:01:01,346 E 6977 7003] logging.cc:484:     @     0x79f4f868fa5b        128  boost::asio::detail::scheduler::do_run_one()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m [2025-03-07 06:01:01,346 E 6977 7003] logging.cc:484:     @     0x79f4f86913d9        288  boost::asio::detail::scheduler::run()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m [2025-03-07 06:01:01,346 E 6977 7003] logging.cc:484:     @     0x79f4f8691ae2         96  boost::asio::io_context::run()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m [2025-03-07 06:01:01,346 E 6977 7003] logging.cc:484:     @     0x79f4f7bb81f1       1280  ray::core::CoreWorker::RunIOService()\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m [2025-03-07 06:01:01,346 E 6977 7003] logging.cc:484:     @     0x79f4f80d6620         64  thread_proxy\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m [2025-03-07 06:01:01,347 E 6977 7003] logging.cc:484:     @     0x79f4f9628ac3  (unknown)  (unknown)\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m Fatal Python error: Segmentation fault\n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m \n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m \n",
            "\u001b[36m(train_cifar100 pid=6977)\u001b[0m Extension modules: msgpack._cmsgpack, google._upb._message, psutil._psutil_linux, psutil._psutil_posix, setproctitle, yaml._yaml, zstandard.backend_c, charset_normalizer.md, ray._raylet, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, pyarrow.lib, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pyarrow._compute, pandas._libs.ops, numexpr.interpreter, bottleneck.move, bottleneck.nonreduce, bottleneck.nonreduce_axis, bottleneck.reduce, pandas._libs.hashing, pandas._libs.arrays, pandas._libs.tslib, pandas._libs.sparse, pandas._libs.internals, pandas._libs.indexing, pandas._libs.index, pandas._libs.writers, pandas._libs.join, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.json, pandas._libs.parsers, pandas._libs.testing, pyarrow._fs, pyarrow._azurefs, pyarrow._hdfs, pyarrow._gcsfs, pyarrow._s3fs, pyarrow._parquet, cython.cimports.libc.math, pyarrow._json, torch._C, torch._C._dynamo.autograd_compiler, torch._C._dynamo.eval_frame, torch._C._dynamo.guards, torch._C._dynamo.utils, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special (total: 88)\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Trial train_cifar100_7b6d0_00002 errored after 0 iterations at 2025-03-07 06:01:01. Total running time: 27s\n",
            "Error file: /tmp/ray/session_2025-03-07_05-45-45_878621_2122/artifacts/2025-03-07_06-00-33/train_cifar100_2025-03-07_06-00-33/driver_artifacts/train_cifar100_7b6d0_00002_2_batch_size=1000,hidden_activation=Sigmoid,lr=0.0081,optimizer=Adam,units=240_2025-03-07_06-00-33/error.txt\n",
            "\n",
            "Trial status: 3 ERROR | 7 PENDING\n",
            "Current time: 2025-03-07 06:01:03. Total running time: 30s\n",
            "Logical resource usage: 2.0/2 CPUs, 0/0 GPUs\n",
            "+------------------------------------------------------------------------------------------------------------------+\n",
            "| Trial name                   status       units   hidden_activation     optimizer       batch_size            lr |\n",
            "+------------------------------------------------------------------------------------------------------------------+\n",
            "| train_cifar100_7b6d0_00003   PENDING        240   Sigmoid               Adam                  1000   0.0836389   |\n",
            "| train_cifar100_7b6d0_00004   PENDING        120   ReLU                  Adam                  2000   0.00461581  |\n",
            "| train_cifar100_7b6d0_00005   PENDING        240   ReLU                  Adam                  2000   0.0110103   |\n",
            "| train_cifar100_7b6d0_00006   PENDING        120   Sigmoid               Adagrad               1000   0.000112485 |\n",
            "| train_cifar100_7b6d0_00007   PENDING        120   Sigmoid               Adam                  2000   0.000224907 |\n",
            "| train_cifar100_7b6d0_00008   PENDING        240   ReLU                  Adagrad               1000   0.0189111   |\n",
            "| train_cifar100_7b6d0_00009   PENDING        240   ReLU                  Adam                  1000   0.0153408   |\n",
            "| train_cifar100_7b6d0_00000   ERROR          120   Sigmoid               Adam                  2000   0.00411973  |\n",
            "| train_cifar100_7b6d0_00001   ERROR          120   ReLU                  Adam                  1000   0.000810627 |\n",
            "| train_cifar100_7b6d0_00002   ERROR          240   Sigmoid               Adam                  1000   0.00814788  |\n",
            "+------------------------------------------------------------------------------------------------------------------+\n",
            "\n",
            "Trial train_cifar100_7b6d0_00003 started with configuration:\n",
            "+-----------------------------------------------------+\n",
            "| Trial train_cifar100_7b6d0_00003 config             |\n",
            "+-----------------------------------------------------+\n",
            "| batch_size                                     1000 |\n",
            "| hidden_activation                           Sigmoid |\n",
            "| lr                                          0.08364 |\n",
            "| optimizer                                      Adam |\n",
            "| units                                           240 |\n",
            "+-----------------------------------------------------+\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-03-07 06:01:11,169\tERROR tune_controller.py:1331 -- Trial task failed for trial train_cifar100_7b6d0_00003\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
            "    result = ray.get(future)\n",
            "             ^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
            "    return func(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/worker.py\", line 2771, in get\n",
            "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
            "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/worker.py\", line 919, in get_objects\n",
            "    raise value.as_instanceof_cause()\n",
            "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=7088, ip=172.28.0.12, actor_id=3237ca2baaaf1bf52b48a51501000000, repr=train_cifar100)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/trainable.py\", line 330, in train\n",
            "    raise skipped from exception_cause(skipped)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/air/_internal/util.py\", line 107, in run\n",
            "    self._ret = self._target(*self._args, **self._kwargs)\n",
            "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
            "    training_func=lambda: self._trainable_func(self.config),\n",
            "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/function_trainable.py\", line 261, in _trainable_func\n",
            "    output = fn()\n",
            "             ^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/util.py\", line 130, in inner\n",
            "    return trainable(config, **fn_kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"<ipython-input-4-011711f2a57e>\", line 94, in train_cifar100\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/train/_internal/session.py\", line 663, in wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^\n",
            "TypeError: report() got an unexpected keyword argument 'loss'\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Trial train_cifar100_7b6d0_00003 errored after 0 iterations at 2025-03-07 06:01:11. Total running time: 37s\n",
            "Error file: /tmp/ray/session_2025-03-07_05-45-45_878621_2122/artifacts/2025-03-07_06-00-33/train_cifar100_2025-03-07_06-00-33/driver_artifacts/train_cifar100_7b6d0_00003_3_batch_size=1000,hidden_activation=Sigmoid,lr=0.0836,optimizer=Adam,units=240_2025-03-07_06-00-33/error.txt\n",
            "\n",
            "Trial train_cifar100_7b6d0_00004 started with configuration:\n",
            "+-----------------------------------------------------+\n",
            "| Trial train_cifar100_7b6d0_00004 config             |\n",
            "+-----------------------------------------------------+\n",
            "| batch_size                                     2000 |\n",
            "| hidden_activation                              ReLU |\n",
            "| lr                                          0.00462 |\n",
            "| optimizer                                      Adam |\n",
            "| units                                           120 |\n",
            "+-----------------------------------------------------+\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-03-07 06:01:19,012\tERROR tune_controller.py:1331 -- Trial task failed for trial train_cifar100_7b6d0_00004\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
            "    result = ray.get(future)\n",
            "             ^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
            "    return func(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/worker.py\", line 2771, in get\n",
            "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
            "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/worker.py\", line 919, in get_objects\n",
            "    raise value.as_instanceof_cause()\n",
            "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=7198, ip=172.28.0.12, actor_id=ea6d6685d6576ecf76d3b4d901000000, repr=train_cifar100)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/trainable.py\", line 330, in train\n",
            "    raise skipped from exception_cause(skipped)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/air/_internal/util.py\", line 107, in run\n",
            "    self._ret = self._target(*self._args, **self._kwargs)\n",
            "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
            "    training_func=lambda: self._trainable_func(self.config),\n",
            "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/function_trainable.py\", line 261, in _trainable_func\n",
            "    output = fn()\n",
            "             ^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/util.py\", line 130, in inner\n",
            "    return trainable(config, **fn_kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"<ipython-input-4-011711f2a57e>\", line 94, in train_cifar100\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/train/_internal/session.py\", line 663, in wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^\n",
            "TypeError: report() got an unexpected keyword argument 'loss'\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Trial train_cifar100_7b6d0_00004 errored after 0 iterations at 2025-03-07 06:01:19. Total running time: 45s\n",
            "Error file: /tmp/ray/session_2025-03-07_05-45-45_878621_2122/artifacts/2025-03-07_06-00-33/train_cifar100_2025-03-07_06-00-33/driver_artifacts/train_cifar100_7b6d0_00004_4_batch_size=2000,hidden_activation=ReLU,lr=0.0046,optimizer=Adam,units=120_2025-03-07_06-00-33/error.txt\n",
            "\n",
            "Trial train_cifar100_7b6d0_00005 started with configuration:\n",
            "+-----------------------------------------------------+\n",
            "| Trial train_cifar100_7b6d0_00005 config             |\n",
            "+-----------------------------------------------------+\n",
            "| batch_size                                     2000 |\n",
            "| hidden_activation                              ReLU |\n",
            "| lr                                          0.01101 |\n",
            "| optimizer                                      Adam |\n",
            "| units                                           240 |\n",
            "+-----------------------------------------------------+\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-03-07 06:01:28,511\tERROR tune_controller.py:1331 -- Trial task failed for trial train_cifar100_7b6d0_00005\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/air/execution/_internal/event_manager.py\", line 110, in resolve_future\n",
            "    result = ray.get(future)\n",
            "             ^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
            "    return func(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/worker.py\", line 2771, in get\n",
            "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
            "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/_private/worker.py\", line 919, in get_objects\n",
            "    raise value.as_instanceof_cause()\n",
            "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=7295, ip=172.28.0.12, actor_id=55588c1ad6510fa7351a9ba601000000, repr=train_cifar100)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/trainable.py\", line 330, in train\n",
            "    raise skipped from exception_cause(skipped)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/air/_internal/util.py\", line 107, in run\n",
            "    self._ret = self._target(*self._args, **self._kwargs)\n",
            "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/function_trainable.py\", line 45, in <lambda>\n",
            "    training_func=lambda: self._trainable_func(self.config),\n",
            "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/function_trainable.py\", line 261, in _trainable_func\n",
            "    output = fn()\n",
            "             ^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/tune/trainable/util.py\", line 130, in inner\n",
            "    return trainable(config, **fn_kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"<ipython-input-4-011711f2a57e>\", line 94, in train_cifar100\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/ray/train/_internal/session.py\", line 663, in wrapper\n",
            "    return fn(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^^\n",
            "TypeError: report() got an unexpected keyword argument 'loss'\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Trial train_cifar100_7b6d0_00005 errored after 0 iterations at 2025-03-07 06:01:28. Total running time: 54s\n",
            "Error file: /tmp/ray/session_2025-03-07_05-45-45_878621_2122/artifacts/2025-03-07_06-00-33/train_cifar100_2025-03-07_06-00-33/driver_artifacts/train_cifar100_7b6d0_00005_5_batch_size=2000,hidden_activation=ReLU,lr=0.0110,optimizer=Adam,units=240_2025-03-07_06-00-33/error.txt\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-03-07 06:01:30,837\tWARNING tune.py:219 -- Stop signal received (e.g. via SIGINT/Ctrl+C), ending Ray Tune run. This will try to checkpoint the experiment state one last time. Press CTRL+C (or send SIGINT/SIGKILL/SIGTERM) to skip. \n",
            "2025-03-07 06:01:30,849\tINFO tune.py:1009 -- Wrote the latest version of all result files and experiment state to '/root/ray_results/train_cifar100_2025-03-07_06-00-33' in 0.0072s.\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Trial status: 6 ERROR | 4 PENDING\n",
            "Current time: 2025-03-07 06:01:30. Total running time: 57s\n",
            "Logical resource usage: 2.0/2 CPUs, 0/0 GPUs\n",
            "+------------------------------------------------------------------------------------------------------------------+\n",
            "| Trial name                   status       units   hidden_activation     optimizer       batch_size            lr |\n",
            "+------------------------------------------------------------------------------------------------------------------+\n",
            "| train_cifar100_7b6d0_00006   PENDING        120   Sigmoid               Adagrad               1000   0.000112485 |\n",
            "| train_cifar100_7b6d0_00007   PENDING        120   Sigmoid               Adam                  2000   0.000224907 |\n",
            "| train_cifar100_7b6d0_00008   PENDING        240   ReLU                  Adagrad               1000   0.0189111   |\n",
            "| train_cifar100_7b6d0_00009   PENDING        240   ReLU                  Adam                  1000   0.0153408   |\n",
            "| train_cifar100_7b6d0_00000   ERROR          120   Sigmoid               Adam                  2000   0.00411973  |\n",
            "| train_cifar100_7b6d0_00001   ERROR          120   ReLU                  Adam                  1000   0.000810627 |\n",
            "| train_cifar100_7b6d0_00002   ERROR          240   Sigmoid               Adam                  1000   0.00814788  |\n",
            "| train_cifar100_7b6d0_00003   ERROR          240   Sigmoid               Adam                  1000   0.0836389   |\n",
            "| train_cifar100_7b6d0_00004   ERROR          120   ReLU                  Adam                  2000   0.00461581  |\n",
            "| train_cifar100_7b6d0_00005   ERROR          240   ReLU                  Adam                  2000   0.0110103   |\n",
            "+------------------------------------------------------------------------------------------------------------------+\n",
            "\n",
            "Number of errored trials: 6\n",
            "+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n",
            "| Trial name                     # failures   error file                                                                                                                                                                                                                                                                 |\n",
            "+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n",
            "| train_cifar100_7b6d0_00000              1   /tmp/ray/session_2025-03-07_05-45-45_878621_2122/artifacts/2025-03-07_06-00-33/train_cifar100_2025-03-07_06-00-33/driver_artifacts/train_cifar100_7b6d0_00000_0_batch_size=2000,hidden_activation=Sigmoid,lr=0.0041,optimizer=Adam,units=120_2025-03-07_06-00-33/error.txt |\n",
            "| train_cifar100_7b6d0_00001              1   /tmp/ray/session_2025-03-07_05-45-45_878621_2122/artifacts/2025-03-07_06-00-33/train_cifar100_2025-03-07_06-00-33/driver_artifacts/train_cifar100_7b6d0_00001_1_batch_size=1000,hidden_activation=ReLU,lr=0.0008,optimizer=Adam,units=120_2025-03-07_06-00-33/error.txt    |\n",
            "| train_cifar100_7b6d0_00002              1   /tmp/ray/session_2025-03-07_05-45-45_878621_2122/artifacts/2025-03-07_06-00-33/train_cifar100_2025-03-07_06-00-33/driver_artifacts/train_cifar100_7b6d0_00002_2_batch_size=1000,hidden_activation=Sigmoid,lr=0.0081,optimizer=Adam,units=240_2025-03-07_06-00-33/error.txt |\n",
            "| train_cifar100_7b6d0_00003              1   /tmp/ray/session_2025-03-07_05-45-45_878621_2122/artifacts/2025-03-07_06-00-33/train_cifar100_2025-03-07_06-00-33/driver_artifacts/train_cifar100_7b6d0_00003_3_batch_size=1000,hidden_activation=Sigmoid,lr=0.0836,optimizer=Adam,units=240_2025-03-07_06-00-33/error.txt |\n",
            "| train_cifar100_7b6d0_00004              1   /tmp/ray/session_2025-03-07_05-45-45_878621_2122/artifacts/2025-03-07_06-00-33/train_cifar100_2025-03-07_06-00-33/driver_artifacts/train_cifar100_7b6d0_00004_4_batch_size=2000,hidden_activation=ReLU,lr=0.0046,optimizer=Adam,units=120_2025-03-07_06-00-33/error.txt    |\n",
            "| train_cifar100_7b6d0_00005              1   /tmp/ray/session_2025-03-07_05-45-45_878621_2122/artifacts/2025-03-07_06-00-33/train_cifar100_2025-03-07_06-00-33/driver_artifacts/train_cifar100_7b6d0_00005_5_batch_size=2000,hidden_activation=ReLU,lr=0.0110,optimizer=Adam,units=240_2025-03-07_06-00-33/error.txt    |\n",
            "+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-03-07 06:01:32,712\tERROR tune.py:1037 -- Trials did not complete: [train_cifar100_7b6d0_00000, train_cifar100_7b6d0_00001, train_cifar100_7b6d0_00002, train_cifar100_7b6d0_00003, train_cifar100_7b6d0_00004, train_cifar100_7b6d0_00005]\n",
            "2025-03-07 06:01:32,715\tWARNING tune.py:1056 -- Experiment has been interrupted, but the most recent state was saved.\n",
            "Resume experiment with: tune.run(..., resume=True)\n",
            "2025-03-07 06:01:32,737\tWARNING experiment_analysis.py:180 -- Failed to fetch metrics for 4 trial(s):\n",
            "- train_cifar100_7b6d0_00006: FileNotFoundError('Could not fetch metrics for train_cifar100_7b6d0_00006: both result.json and progress.csv were not found at /root/ray_results/train_cifar100_2025-03-07_06-00-33/train_cifar100_7b6d0_00006_6_batch_size=1000,hidden_activation=Sigmoid,lr=0.0001,optimizer=Adagrad,units=120_2025-03-07_06-00-33')\n",
            "- train_cifar100_7b6d0_00007: FileNotFoundError('Could not fetch metrics for train_cifar100_7b6d0_00007: both result.json and progress.csv were not found at /root/ray_results/train_cifar100_2025-03-07_06-00-33/train_cifar100_7b6d0_00007_7_batch_size=2000,hidden_activation=Sigmoid,lr=0.0002,optimizer=Adam,units=120_2025-03-07_06-00-33')\n",
            "- train_cifar100_7b6d0_00008: FileNotFoundError('Could not fetch metrics for train_cifar100_7b6d0_00008: both result.json and progress.csv were not found at /root/ray_results/train_cifar100_2025-03-07_06-00-33/train_cifar100_7b6d0_00008_8_batch_size=1000,hidden_activation=ReLU,lr=0.0189,optimizer=Adagrad,units=240_2025-03-07_06-00-33')\n",
            "- train_cifar100_7b6d0_00009: FileNotFoundError('Could not fetch metrics for train_cifar100_7b6d0_00009: both result.json and progress.csv were not found at /root/ray_results/train_cifar100_2025-03-07_06-00-33/train_cifar100_7b6d0_00009_9_batch_size=1000,hidden_activation=ReLU,lr=0.0153,optimizer=Adam,units=240_2025-03-07_06-00-33')\n",
            "2025-03-07 06:01:32,742\tWARNING experiment_analysis.py:558 -- Could not find best trial. Did you pass the correct `metric` parameter?\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n"
          ]
        },
        {
          "output_type": "error",
          "ename": "AttributeError",
          "evalue": "'NoneType' object has no attribute 'config'",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
            "\u001b[0;32m<ipython-input-4-011711f2a57e>\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[1;32m    121\u001b[0m \u001b[0mdf\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0manalysis\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mresults_df\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    122\u001b[0m \u001b[0mbest_trial\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0manalysis\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_best_trial\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'accuracy'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'max'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'last'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 123\u001b[0;31m \u001b[0mbest_config\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mbest_trial\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconfig\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    124\u001b[0m \u001b[0mbest_accuracy\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mbest_trial\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlast_result\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'accuracy'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    125\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mAttributeError\u001b[0m: 'NoneType' object has no attribute 'config'"
          ]
        }
      ],
      "source": [
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.optim as optim\n",
        "import torchvision.transforms as transforms\n",
        "from torch.utils.data import DataLoader, random_split, TensorDataset\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "import pandas as pd\n",
        "import pickle\n",
        "from google.colab import drive\n",
        "\n",
        "# Mount Google Drive\n",
        "drive.mount(\"/content/drive\")\n",
        "\n",
        "# Load CIFAR-100 dataset from Google Drive\n",
        "with open('/content/drive/My Drive/train', 'rb') as file:\n",
        "    train_dict = pickle.load(file, encoding='bytes')\n",
        "\n",
        "with open('/content/drive/My Drive/test', 'rb') as file:\n",
        "    test_dict = pickle.load(file, encoding='bytes')\n",
        "\n",
        "# Extract data and labels\n",
        "train_data = torch.tensor(train_dict[b'data'], dtype=torch.float32).reshape(-1, 3, 32, 32) / 255.0\n",
        "train_labels = torch.tensor(train_dict[b'fine_labels'], dtype=torch.long)\n",
        "test_data = torch.tensor(test_dict[b'data'], dtype=torch.float32).reshape(-1, 3, 32, 32) / 255.0\n",
        "test_labels = torch.tensor(test_dict[b'fine_labels'], dtype=torch.long)\n",
        "\n",
        "# Create datasets\n",
        "train_dataset = TensorDataset(train_data, train_labels)\n",
        "test_dataset = TensorDataset(test_data, test_labels)\n",
        "\n",
        "class CIFAR100Net(nn.Module):\n",
        "    def __init__(self, units, hidden_activation):\n",
        "        super(CIFAR100Net, self).__init__()\n",
        "        self.hidden_activation = getattr(nn, hidden_activation)()\n",
        "        self.fc1 = nn.Linear(3 * 32 * 32, units)\n",
        "        self.hidden_layers = nn.ModuleList([nn.Linear(units, units) for _ in range(4)])\n",
        "        self.output_layer = nn.Linear(units, 100)\n",
        "\n",
        "    def forward(self, x):\n",
        "        x = x.view(-1, 3 * 32 * 32)\n",
        "        x = self.hidden_activation(self.fc1(x))\n",
        "        for layer in self.hidden_layers:\n",
        "            x = self.hidden_activation(layer(x))\n",
        "        x = self.output_layer(x)  # No softmax, since CrossEntropyLoss expects raw logits\n",
        "        return x\n",
        "\n",
        "def train_cifar100(model, train_loader, val_loader, optimizer, criterion, device, epochs=10):\n",
        "    history = {'epoch': [], 'accuracy': []}\n",
        "    for epoch in range(epochs):\n",
        "        model.train()\n",
        "        running_loss = 0.0\n",
        "        for inputs, labels in train_loader:\n",
        "            inputs, labels = inputs.to(device), labels.to(device)\n",
        "            optimizer.zero_grad()\n",
        "            outputs = model(inputs)\n",
        "            loss = criterion(outputs, labels)\n",
        "            loss.backward()\n",
        "            optimizer.step()\n",
        "            running_loss += loss.item()\n",
        "\n",
        "        val_loss = 0.0\n",
        "        correct = 0\n",
        "        total = 0\n",
        "        model.eval()\n",
        "        with torch.no_grad():\n",
        "            for inputs, labels in val_loader:\n",
        "                inputs, labels = inputs.to(device), labels.to(device)\n",
        "                outputs = model(inputs)\n",
        "                loss = criterion(outputs, labels)\n",
        "                val_loss += loss.item()\n",
        "                _, predicted = torch.max(outputs.data, 1)\n",
        "                total += labels.size(0)\n",
        "                correct += (predicted == labels).sum().item()\n",
        "\n",
        "        val_loss /= len(val_loader)\n",
        "        val_accuracy = correct / total\n",
        "        history['epoch'].append(epoch + 1)\n",
        "        history['accuracy'].append(val_accuracy)\n",
        "        print(f'Epoch {epoch+1}, Loss: {val_loss:.4f}, Accuracy: {val_accuracy:.4f}')\n",
        "    return history\n",
        "\n",
        "# Set hyperparameters\n",
        "config = {\n",
        "    'units': 240,\n",
        "    'hidden_activation': 'ReLU',\n",
        "    'optimizer': 'Adam',\n",
        "    'batch_size': 1000,\n",
        "    'lr': 0.001\n",
        "}\n",
        "\n",
        "# Prepare data\n",
        "train_size = int(0.8 * len(train_dataset))\n",
        "val_size = len(train_dataset) - train_size\n",
        "train_subset, val_subset = random_split(train_dataset, [train_size, val_size])\n",
        "\n",
        "train_loader = DataLoader(train_subset, batch_size=config['batch_size'], shuffle=True)\n",
        "val_loader = DataLoader(val_subset, batch_size=config['batch_size'], shuffle=False)\n",
        "test_loader = DataLoader(test_dataset, batch_size=config['batch_size'], shuffle=False)\n",
        "\n",
        "# Initialize model\n",
        "device = torch.device(\"cpu\")\n",
        "model = CIFAR100Net(config['units'], config['hidden_activation']).to(device)\n",
        "criterion = nn.CrossEntropyLoss()\n",
        "optimizer = getattr(optim, config['optimizer'])(model.parameters(), lr=config['lr'])\n",
        "\n",
        "# Train model\n",
        "history = train_cifar100(model, train_loader, val_loader, optimizer, criterion, device, epochs=10)\n",
        "\n",
        "# Evaluate model\n",
        "correct = 0\n",
        "total = 0\n",
        "model.eval()\n",
        "with torch.no_grad():\n",
        "    for inputs, labels in test_loader:\n",
        "        inputs, labels = inputs.to(device), labels.to(device)\n",
        "        outputs = model(inputs)\n",
        "        _, predicted = torch.max(outputs.data, 1)\n",
        "        total += labels.size(0)\n",
        "        correct += (predicted == labels).sum().item()\n",
        "\n",
        "best_accuracy = correct / total\n",
        "print(f'Best Hyperparameters: {config}')\n",
        "print(f'Best Accuracy: {best_accuracy:.4f}')\n",
        "\n",
        "# Plot results\n",
        "df = pd.DataFrame(history)\n",
        "plt.figure(figsize=(10, 5))\n",
        "sns.lineplot(data=df, x='epoch', y='accuracy')\n",
        "plt.xlabel('Training Iteration')\n",
        "plt.ylabel('Validation Accuracy')\n",
        "plt.title('Hyperparameter Tuning Results')\n",
        "plt.grid()\n",
        "plt.savefig(\"/content/drive/My Drive/hyperparameter_tuning_plot.png\", dpi=300)\n",
        "plt.show()"
      ]
    }
  ]
}